### PR TITLE
Add a comment to the pull request flow when a workflow run completes

### PR DESCRIPTION
**Pull request by geoand**
Marking as draft because:

1) I am not completely sure the message-id handling is correct
2) I have no idea how to test this

### CODE REVIEW

**Comment by geoand** [comment]
cc @gsmet

**Comment by geoand** [comment]
Exactly, I often forget about PRs

**Comment by geoand** [comment]
Thanks!

**Comment by gsmet** [comment]
Thanks to you. I released and will wait for it to hit Central before pushing a new version of the bot.

**Comment by geoand** [comment]
🎉🎉🎉

**Comment by gsmet** [comment]
I just deployed it!

**Comment by geoand** [comment]
Super quick!

**Pull request merged**
