### PR TITLE
Add support for flaky tests

### PR DESCRIPTION
**Pull request by gsmet**

### CODE REVIEW

**Comment by michalvavrik** [comment]
FYI we are eagerly expecting this feature as we re-run failing tests with the FailSafe plugin and already are using build-reported, therefore being able to see flaky tests in reported would be helpful. Thank you for looking at it.

**Comment by gsmet** [comment]
Thanks for the input @michalvavrik . I need to finalize a few things and test it before merging. I hope to get it done this week if I’m not too sidetracked.

**Comment by gsmet** [comment]
@michalvavrik 3.4.1 should work for you I think. Let me know if you have any issue.

**Comment by michalvavrik** [comment]
> @michalvavrik 3.4.1 should work for you I think. Let me know if you have any issue.

Will do, thank you.

**Pull request merged**
